
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Users/kofisampong/Applications/CLion.app/Contents/bin/cmake/mac/aarch64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 23.0.0 - arm64
...
